# Generated by Django 4.2.5 on 2023-09-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Германия", "Германия"),
                            ("Турция", "Турция"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=20,
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="Wear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "size",
                    models.CharField(max_length=20, null=True, verbose_name="Размер"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Белый", "Белый"),
                            ("Черный", "Черный"),
                            ("Желтый", "Желтый"),
                            ("Зеленый", "Зеленый"),
                            ("Синий", "Синий"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=10,
                        verbose_name="Цвет",
                    ),
                ),
                (
                    "material",
                    models.CharField(max_length=20, null=True, verbose_name="Материал"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unisex", "Unisex"),
                        ],
                        default="Unisex",
                        max_length=6,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.CharField(max_length=10, null=True, verbose_name="Возраст"),
                ),
                (
                    "brand",
                    models.CharField(max_length=20, null=True, verbose_name="Бренд"),
                ),
                ("price", models.IntegerField(null=True, verbose_name="Цена")),
                (
                    "description",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/wear/img.png",
                        null=True,
                        upload_to="wear/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bodysuit",
            fields=[
                (
                    "wear_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.wear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Боди",
                "verbose_name_plural": "Боди",
            },
            bases=("store.wear",),
        ),
        migrations.CreateModel(
            name="Jacket",
            fields=[
                (
                    "wear_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.wear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Куртка",
                "verbose_name_plural": "Куртки",
            },
            bases=("store.wear",),
        ),
        migrations.CreateModel(
            name="Pants",
            fields=[
                (
                    "wear_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.wear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штаны",
                "verbose_name_plural": "Штаны",
            },
            bases=("store.wear",),
        ),
        migrations.CreateModel(
            name="TShort",
            fields=[
                (
                    "wear_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.wear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Майка",
                "verbose_name_plural": "Майки",
            },
            bases=("store.wear",),
        ),
    ]
