# Generated by Django 4.2.5 on 2023-10-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('country', models.CharField(choices=[('Германия', 'Германия'), ('Турция', 'Турция'), ('Китай', 'Китай'), ('-', '-')], default='-', max_length=20, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('material', models.CharField(max_length=20, null=True, verbose_name='Материал')),
                ('number_of_figures', models.IntegerField(default=1, verbose_name='Количество фигур')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dolls/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Кукла',
                'verbose_name_plural': 'Куклы',
            },
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('size', models.CharField(choices=[('50', '50'), ('56', '56'), ('62', '62'), ('68', '68'), ('74', '74'), ('80', '90'), ('86', '80'), ('92', '92'), ('98', '98'), ('104', '104'), ('110', '110'), ('116', '116'), ('122', '122'), ('128', '128'), ('134', '134'), ('140', '140'), ('146', '146'), ('152', '152')], max_length=3, verbose_name='Размер')),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Желтый', 'Желтый'), ('Зеленый', 'Зеленый'), ('Синий', 'Синий'), ('Коричневый', 'Коричневый'), ('Оранжевый', 'Оранжевый'), ('Фиолетовый', 'Фиолетовый'), ('Серый', 'Серый'), ('Розовый', 'Розовый'), ('-', '-')], default='-', max_length=10, verbose_name='Цвет')),
                ('material', models.CharField(max_length=20, null=True, verbose_name='Материал')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=6, verbose_name='Пол')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='Возраст')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='media/wear/майка.png', null=True, upload_to='wear/', verbose_name='Фотография')),
                ('quantity', models.PositiveIntegerField(default=0, null=True, verbose_name='Количество')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('doll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.doll')),
            ],
            options={
                'verbose_name': 'Ангел',
                'verbose_name_plural': 'Ангелы',
            },
            bases=('store.doll',),
        ),
        migrations.CreateModel(
            name='Bodysuit',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Боди, слип',
                'verbose_name_plural': 'Боди, слипы',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='ClothingSet',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Костюм/комплект',
                'verbose_name_plural': 'Костюмы/комплекты',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('doll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.doll')),
            ],
            options={
                'verbose_name': 'Семья кукол',
                'verbose_name_plural': 'Семьи кукол',
            },
            bases=('store.doll',),
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Верхняя одежда',
                'verbose_name_plural': 'Верхняя одежда',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='LongSleeve',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Лонгслив',
                'verbose_name_plural': 'Лонгсливы',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Overall',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Комбинезон',
                'verbose_name_plural': 'Комбинезоны',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Штаны, джинсы',
                'verbose_name_plural': 'Штаны, джинсы',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Robe',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Платье',
                'verbose_name_plural': 'Платья',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='SocksTights',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Носки/колготки',
                'verbose_name_plural': 'Носки/колготки',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Sweatshirt',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Cвитшот',
                'verbose_name_plural': 'Cвитшоты',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='TShort',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Майка',
                'verbose_name_plural': 'Майки',
            },
            bases=('store.wear',),
        ),
        migrations.CreateModel(
            name='Underwear',
            fields=[
                ('wear_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.wear')),
            ],
            options={
                'verbose_name': 'Нижнее белье',
                'verbose_name_plural': 'Нижнее белье',
            },
            bases=('store.wear',),
        ),
    ]
