# Generated by Django 4.2.5 on 2023-09-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wear",
            name="brand",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.brand",
                verbose_name="Бренд",
            ),
            preserve_default=False,
        ),
    ]
