# Generated by Django 4.2.5 on 2023-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doll',
            name='status',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('В корзине', 'В корзине'), ('Продана', 'Продана'), ('На складе', 'На складе')], default='В наличии', max_length=40, verbose_name='Статус'),
        ),
    ]
