# Generated by Django 4.2.5 on 2023-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_wear_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.CharField(
                choices=[
                    ("Германия", "Германия"),
                    ("Турция", "Турция"),
                    ("Китай", "Китай"),
                    ("-", "-"),
                ],
                default="-",
                max_length=20,
                verbose_name="Страна",
            ),
        ),
    ]
