# Generated by Django 4.2.5 on 2023-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_doll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doll',
            name='material',
            field=models.CharField(default='Макраме', max_length=20, null=True, verbose_name='Материал'),
        ),
    ]
