# Generated by Django 4.2.5 on 2023-09-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_brand_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wear",
            name="size",
            field=models.CharField(
                choices=[
                    (50, 50),
                    (56, 56),
                    (62, 62),
                    (68, 68),
                    (74, 74),
                    (80, 90),
                    (86, 80),
                    (92, 92),
                    (98, 98),
                    (104, 104),
                    (110, 110),
                    (116, 116),
                    (122, 122),
                    (128, 128),
                    (134, 134),
                    (140, 140),
                    (146, 146),
                    (152, 152),
                ],
                default=None,
                max_length=2,
                verbose_name="Размер",
            ),
            preserve_default=False,
        ),
    ]
