# Generated by Django 4.2.5 on 2023-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_doll_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wear',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='wear/', verbose_name='Фотография'),
        ),
    ]
