# Generated by Django 4.2.5 on 2023-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_wear_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wear",
            name="color",
            field=models.CharField(
                choices=[
                    ("Белый", "Белый"),
                    ("Черный", "Черный"),
                    ("Желтый", "Желтый"),
                    ("Зеленый", "Зеленый"),
                    ("Синий", "Синий"),
                    ("Коричневый", "Коричневый"),
                    ("Оранжевый", "Оранжевый"),
                    ("Фиолетовый", "Фиолетовый"),
                    ("Серый", "Серый"),
                    ("Розовый", "Розовый"),
                    ("-", "-"),
                ],
                default="-",
                max_length=10,
                verbose_name="Цвет",
            ),
        ),
    ]
