# Generated by Django 4.2.5 on 2023-10-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_clothingset_longsleeve_overall_robe_sockstights_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, null=True, verbose_name="Название"),
                ),
                (
                    "material",
                    models.CharField(max_length=20, null=True, verbose_name="Материал"),
                ),
                (
                    "number_of_figures",
                    models.IntegerField(default=1, verbose_name="Количество фигур"),
                ),
                ("price", models.IntegerField(null=True, verbose_name="Цена")),
                (
                    "description",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Описание"
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="dolls/")),
            ],
        ),
        migrations.CreateModel(
            name="Angel",
            fields=[
                (
                    "doll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.doll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ангел",
                "verbose_name_plural": "Ангелы",
            },
            bases=("store.doll",),
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "doll_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="store.doll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Семья",
                "verbose_name_plural": "Семьи",
            },
            bases=("store.doll",),
        ),
    ]
