# Generated by Django 4.2.5 on 2023-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_doll_angel_family"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doll",
            options={"verbose_name": "Кукла", "verbose_name_plural": "Куклы"},
        ),
        migrations.AlterModelOptions(
            name="family",
            options={
                "verbose_name": "Семья кукол",
                "verbose_name_plural": "Семьи кукол",
            },
        ),
        migrations.AlterField(
            model_name="doll",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="dolls/", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="wear",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/wear/майка.png",
                null=True,
                upload_to="wear/",
                verbose_name="Фотография",
            ),
        ),
    ]
