# Generated by Django 4.2.5 on 2023-10-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_doll_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wear',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество'),
        ),
    ]
