version: "3.9"

services:
  db:

    build:
      context: .
    ports:
      - "5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


    volumes:
      - /postgres_db:/var/lib/postgresql/data

