version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_completed_successfully
      migrations:
        condition: service_completed_successfully
    command: python3 manage.py runserver

  migrations:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .

    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
