# Generated by Django 4.2.5 on 2023-10-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(verbose_name='ID чата')),
                ('tg_user_id', models.IntegerField(unique=True, verbose_name='Телеграм-id')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Юзернейм в ТГ')),
                ('phone', models.CharField(max_length=30, null=True, verbose_name='Телефон')),
                ('verification_code', models.CharField(max_length=20, null=True, verbose_name='Верифицационный код')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
    ]
