# Generated by Django 4.2.5 on 2023-10-01 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="first_name",
            field=models.CharField(max_length=150, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="last_name",
            field=models.CharField(max_length=150, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_chat_id",
            field=models.IntegerField(verbose_name="ID чата"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="tg_user_id",
            field=models.IntegerField(unique=True, verbose_name="Телеграм-id"),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ID пользователя на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="username",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Юзернейм в ТГ"
            ),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="verification_code",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Верифицационный код"
            ),
        ),
    ]
