# Generated by Django 4.2.5 on 2023-10-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_tguser_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tguser",
            old_name="phonenumber",
            new_name="phone",
        ),
    ]
