# Generated by Django 4.2.5 on 2023-11-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetoclient',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
