name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v2
      # Собираем докер-образ
      - name: docker build
        run: docker build -t  amanitocornholio/bot_fox_chest:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      # Пуш в Docker hub
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#     # Отправляем образ в Docker hub
      - name: docker push
        run: docker push amanitocornholio/fox_chest:$GITHUB_REF_NAME-$GITHUB_RUN_ID
