name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Копируем код из репозитория в runner
      - name: clone code
        uses: actions/checkout@v2
      # Собираем докер-образ
      - name: docker build
        run: docker build -t  amanitocornholio/bot_fox_chest:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      # Пуш в Docker hub
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#     # Отправляем образ в Docker hub
      - name: docker push
        run: docker push amanitocornholio/bot_fox_chest:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-22.04.2
    needs: build_and_push
    env:
      DB_USER: postgres
      DB_PASSWORD: ${{ secrets.DB_FOX_PASSWORD }}
      DB_NAME: ${{ secrets.DB_FOX_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FOX_SERVER_HOST }}
          username: ${{ secrets.FOX_SERVER_USERNAME }}
          password: ${{ secrets.FOX_SERVER_PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: "todolist_ci/"
          strip_components: 1
