# Generated by Django 4.2.5 on 2023-10-02 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bot", "0002_alter_tguser_first_name_alter_tguser_last_name_and_more"),
        ("store", "0007_alter_wear_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "updated",
                    models.DateTimeField(verbose_name="Дата последнего обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создан", "Создан"),
                            ("В процессе", "В процессе"),
                            ("Выполнен", "Выполнен"),
                            ("Отменён", "Отменён"),
                        ],
                        default="Создан",
                        max_length=20,
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "goods",
                    models.ManyToManyField(to="store.wear", verbose_name="Товары"),
                ),
                (
                    "tg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.tguser",
                        verbose_name="Пользователь Телеграм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
