# Generated by Django 4.2.5 on 2023-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwearitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
