# Generated by Django 4.2.5 on 2023-10-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_orderwearitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwearitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
