# Generated by Django 4.2.5 on 2023-10-02 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_wear_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0002_order_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="executor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="goods",
            field=models.ManyToManyField(
                null=True, to="store.wear", verbose_name="Товары"
            ),
        ),
    ]
