# Generated by Django 4.2.5 on 2023-10-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_wear_size"),
        ("sales", "0004_alter_order_executor_alter_order_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="goods",
            field=models.ManyToManyField(
                blank=True, to="store.wear", verbose_name="Товары"
            ),
        ),
    ]
