# Generated by Django 4.2.5 on 2023-11-05 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('bot', '0002_initial'),
        ('sales', '0004_order_total_units_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ одежды', 'verbose_name_plural': 'Заказы одежды'},
        ),
        migrations.CreateModel(
            name='OrderDolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(verbose_name='Дата последнего обновления')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Оплачен', 'Оплачен'), ('В процессе', 'В процессе'), ('Выполнен', 'Выполнен'), ('Отменён', 'Отменён')], default='Создан', max_length=20, verbose_name='Заказ')),
                ('delivery_method', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Почта России', 'Почта России'), ('Boxberry', 'Boxberry'), ('CДЭК', 'CДЭК'), ('Авито', 'Авито'), ('Неизвестно', 'Неизвестно')], default='Неизвестно', max_length=20, verbose_name='Способ доставки')),
                ('receiver', models.CharField(max_length=50, null=True, verbose_name='Получатель')),
                ('phone_receiver', models.CharField(max_length=50, null=True, verbose_name='Телефон получателя')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('total_price', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('discount', models.CharField(default='Нет', max_length=100, verbose_name='Скидка')),
                ('total_units_quantity', models.PositiveIntegerField(default=0)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('goods', models.ManyToManyField(blank=True, to='store.doll', verbose_name='Товары в корзине')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.tguser', verbose_name='Пользователь Телеграм')),
            ],
            options={
                'verbose_name': 'Заказ кукол',
                'verbose_name_plural': 'Заказы кукол',
            },
        ),
    ]
