# Generated by Django 4.2.5 on 2023-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_order_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создан", "Создан"),
                    ("Оплачен", "Оплачен"),
                    ("В процессе", "В процессе"),
                    ("Выполнен", "Выполнен"),
                    ("Отменён", "Отменён"),
                ],
                default="Создан",
                max_length=20,
                verbose_name="Заказ",
            ),
        ),
    ]
