# Generated by Django 4.2.5 on 2023-10-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_wear_size"),
        ("bot", "0002_alter_tguser_first_name_alter_tguser_last_name_and_more"),
        ("sales", "0006_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goods",
                    models.ManyToManyField(
                        blank=True, to="store.wear", verbose_name="Товары"
                    ),
                ),
                (
                    "tg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.tguser",
                        verbose_name="Пользователь Телеграм",
                    ),
                ),
            ],
        ),
    ]
