# Generated by Django 4.2.5 on 2023-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_order_delivery_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("Самовывоз", "Самовывоз"),
                    ("Почта России", "Почта России"),
                    ("Boxberry", "Boxberry"),
                    ("CДЭК", "CДЭК"),
                    ("Авито", "Авито"),
                    ("Неизвестно", "Неизвестно"),
                ],
                default="Неизвестно",
                max_length=20,
                verbose_name="Способ доставки",
            ),
        ),
    ]
