# Generated by Django 4.2.5 on 2023-10-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_alter_order_delivery_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
