# Generated by Django 4.2.5 on 2023-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=200, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_receiver",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Телефон получателя"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receiver",
            field=models.CharField(max_length=50, null=True, verbose_name="Получатель"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
